// Auto-generated from @unicode/unicode-16.0.0
// Do not edit manually. Run: npx tsx scripts/generate-blocks.ts

export type UnicodeBlock = {
  name: string
  displayName: string
  start: number
  end: number
}

export const UNICODE_BLOCKS: UnicodeBlock[] = [
  { name: 'Basic_Latin', displayName: 'Basic Latin', start: 0x0000, end: 0x007F },
  { name: 'Latin_1_Supplement', displayName: 'Latin 1 Supplement', start: 0x0080, end: 0x00FF },
  { name: 'Latin_Extended_A', displayName: 'Latin Extended A', start: 0x0100, end: 0x017F },
  { name: 'Latin_Extended_B', displayName: 'Latin Extended B', start: 0x0180, end: 0x024F },
  { name: 'IPA_Extensions', displayName: 'IPA Extensions', start: 0x0250, end: 0x02AF },
  { name: 'Spacing_Modifier_Letters', displayName: 'Spacing Modifier Letters', start: 0x02B0, end: 0x02FF },
  { name: 'Combining_Diacritical_Marks', displayName: 'Combining Diacritical Marks', start: 0x0300, end: 0x036F },
  { name: 'Greek_And_Coptic', displayName: 'Greek And Coptic', start: 0x0370, end: 0x03FF },
  { name: 'Cyrillic', displayName: 'Cyrillic', start: 0x0400, end: 0x04FF },
  { name: 'Cyrillic_Supplement', displayName: 'Cyrillic Supplement', start: 0x0500, end: 0x052F },
  { name: 'Armenian', displayName: 'Armenian', start: 0x0530, end: 0x058F },
  { name: 'Hebrew', displayName: 'Hebrew', start: 0x0590, end: 0x05FF },
  { name: 'Arabic', displayName: 'Arabic', start: 0x0600, end: 0x06FF },
  { name: 'Syriac', displayName: 'Syriac', start: 0x0700, end: 0x074F },
  { name: 'Arabic_Supplement', displayName: 'Arabic Supplement', start: 0x0750, end: 0x077F },
  { name: 'Thaana', displayName: 'Thaana', start: 0x0780, end: 0x07BF },
  { name: 'NKo', displayName: 'NKo', start: 0x07C0, end: 0x07FF },
  { name: 'Samaritan', displayName: 'Samaritan', start: 0x0800, end: 0x083F },
  { name: 'Mandaic', displayName: 'Mandaic', start: 0x0840, end: 0x085F },
  { name: 'Syriac_Supplement', displayName: 'Syriac Supplement', start: 0x0860, end: 0x086F },
  { name: 'Arabic_Extended_B', displayName: 'Arabic Extended B', start: 0x0870, end: 0x089F },
  { name: 'Arabic_Extended_A', displayName: 'Arabic Extended A', start: 0x08A0, end: 0x08FF },
  { name: 'Devanagari', displayName: 'Devanagari', start: 0x0900, end: 0x097F },
  { name: 'Bengali', displayName: 'Bengali', start: 0x0980, end: 0x09FF },
  { name: 'Gurmukhi', displayName: 'Gurmukhi', start: 0x0A00, end: 0x0A7F },
  { name: 'Gujarati', displayName: 'Gujarati', start: 0x0A80, end: 0x0AFF },
  { name: 'Oriya', displayName: 'Oriya', start: 0x0B00, end: 0x0B7F },
  { name: 'Tamil', displayName: 'Tamil', start: 0x0B80, end: 0x0BFF },
  { name: 'Telugu', displayName: 'Telugu', start: 0x0C00, end: 0x0C7F },
  { name: 'Kannada', displayName: 'Kannada', start: 0x0C80, end: 0x0CFF },
  { name: 'Malayalam', displayName: 'Malayalam', start: 0x0D00, end: 0x0D7F },
  { name: 'Sinhala', displayName: 'Sinhala', start: 0x0D80, end: 0x0DFF },
  { name: 'Thai', displayName: 'Thai', start: 0x0E00, end: 0x0E7F },
  { name: 'Lao', displayName: 'Lao', start: 0x0E80, end: 0x0EFF },
  { name: 'Tibetan', displayName: 'Tibetan', start: 0x0F00, end: 0x0FFF },
  { name: 'Myanmar', displayName: 'Myanmar', start: 0x1000, end: 0x109F },
  { name: 'Georgian', displayName: 'Georgian', start: 0x10A0, end: 0x10FF },
  { name: 'Hangul_Jamo', displayName: 'Hangul Jamo', start: 0x1100, end: 0x11FF },
  { name: 'Ethiopic', displayName: 'Ethiopic', start: 0x1200, end: 0x137F },
  { name: 'Ethiopic_Supplement', displayName: 'Ethiopic Supplement', start: 0x1380, end: 0x139F },
  { name: 'Cherokee', displayName: 'Cherokee', start: 0x13A0, end: 0x13FF },
  { name: 'Unified_Canadian_Aboriginal_Syllabics', displayName: 'Unified Canadian Aboriginal Syllabics', start: 0x1400, end: 0x167F },
  { name: 'Ogham', displayName: 'Ogham', start: 0x1680, end: 0x169F },
  { name: 'Runic', displayName: 'Runic', start: 0x16A0, end: 0x16FF },
  { name: 'Tagalog', displayName: 'Tagalog', start: 0x1700, end: 0x171F },
  { name: 'Hanunoo', displayName: 'Hanunoo', start: 0x1720, end: 0x173F },
  { name: 'Buhid', displayName: 'Buhid', start: 0x1740, end: 0x175F },
  { name: 'Tagbanwa', displayName: 'Tagbanwa', start: 0x1760, end: 0x177F },
  { name: 'Khmer', displayName: 'Khmer', start: 0x1780, end: 0x17FF },
  { name: 'Mongolian', displayName: 'Mongolian', start: 0x1800, end: 0x18AF },
  { name: 'Unified_Canadian_Aboriginal_Syllabics_Extended', displayName: 'Unified Canadian Aboriginal Syllabics Extended', start: 0x18B0, end: 0x18FF },
  { name: 'Limbu', displayName: 'Limbu', start: 0x1900, end: 0x194F },
  { name: 'Tai_Le', displayName: 'Tai Le', start: 0x1950, end: 0x197F },
  { name: 'New_Tai_Lue', displayName: 'New Tai Lue', start: 0x1980, end: 0x19DF },
  { name: 'Khmer_Symbols', displayName: 'Khmer Symbols', start: 0x19E0, end: 0x19FF },
  { name: 'Buginese', displayName: 'Buginese', start: 0x1A00, end: 0x1A1F },
  { name: 'Tai_Tham', displayName: 'Tai Tham', start: 0x1A20, end: 0x1AAF },
  { name: 'Combining_Diacritical_Marks_Extended', displayName: 'Combining Diacritical Marks Extended', start: 0x1AB0, end: 0x1AFF },
  { name: 'Balinese', displayName: 'Balinese', start: 0x1B00, end: 0x1B7F },
  { name: 'Sundanese', displayName: 'Sundanese', start: 0x1B80, end: 0x1BBF },
  { name: 'Batak', displayName: 'Batak', start: 0x1BC0, end: 0x1BFF },
  { name: 'Lepcha', displayName: 'Lepcha', start: 0x1C00, end: 0x1C4F },
  { name: 'Ol_Chiki', displayName: 'Ol Chiki', start: 0x1C50, end: 0x1C7F },
  { name: 'Cyrillic_Extended_C', displayName: 'Cyrillic Extended C', start: 0x1C80, end: 0x1C8F },
  { name: 'Georgian_Extended', displayName: 'Georgian Extended', start: 0x1C90, end: 0x1CBF },
  { name: 'Sundanese_Supplement', displayName: 'Sundanese Supplement', start: 0x1CC0, end: 0x1CCF },
  { name: 'Vedic_Extensions', displayName: 'Vedic Extensions', start: 0x1CD0, end: 0x1CFF },
  { name: 'Phonetic_Extensions', displayName: 'Phonetic Extensions', start: 0x1D00, end: 0x1D7F },
  { name: 'Phonetic_Extensions_Supplement', displayName: 'Phonetic Extensions Supplement', start: 0x1D80, end: 0x1DBF },
  { name: 'Combining_Diacritical_Marks_Supplement', displayName: 'Combining Diacritical Marks Supplement', start: 0x1DC0, end: 0x1DFF },
  { name: 'Latin_Extended_Additional', displayName: 'Latin Extended Additional', start: 0x1E00, end: 0x1EFF },
  { name: 'Greek_Extended', displayName: 'Greek Extended', start: 0x1F00, end: 0x1FFF },
  { name: 'General_Punctuation', displayName: 'General Punctuation', start: 0x2000, end: 0x206F },
  { name: 'Superscripts_And_Subscripts', displayName: 'Superscripts And Subscripts', start: 0x2070, end: 0x209F },
  { name: 'Currency_Symbols', displayName: 'Currency Symbols', start: 0x20A0, end: 0x20CF },
  { name: 'Combining_Diacritical_Marks_For_Symbols', displayName: 'Combining Diacritical Marks For Symbols', start: 0x20D0, end: 0x20FF },
  { name: 'Letterlike_Symbols', displayName: 'Letterlike Symbols', start: 0x2100, end: 0x214F },
  { name: 'Number_Forms', displayName: 'Number Forms', start: 0x2150, end: 0x218F },
  { name: 'Arrows', displayName: 'Arrows', start: 0x2190, end: 0x21FF },
  { name: 'Mathematical_Operators', displayName: 'Mathematical Operators', start: 0x2200, end: 0x22FF },
  { name: 'Miscellaneous_Technical', displayName: 'Miscellaneous Technical', start: 0x2300, end: 0x23FF },
  { name: 'Control_Pictures', displayName: 'Control Pictures', start: 0x2400, end: 0x243F },
  { name: 'Optical_Character_Recognition', displayName: 'Optical Character Recognition', start: 0x2440, end: 0x245F },
  { name: 'Enclosed_Alphanumerics', displayName: 'Enclosed Alphanumerics', start: 0x2460, end: 0x24FF },
  { name: 'Box_Drawing', displayName: 'Box Drawing', start: 0x2500, end: 0x257F },
  { name: 'Block_Elements', displayName: 'Block Elements', start: 0x2580, end: 0x259F },
  { name: 'Geometric_Shapes', displayName: 'Geometric Shapes', start: 0x25A0, end: 0x25FF },
  { name: 'Miscellaneous_Symbols', displayName: 'Miscellaneous Symbols', start: 0x2600, end: 0x26FF },
  { name: 'Dingbats', displayName: 'Dingbats', start: 0x2700, end: 0x27BF },
  { name: 'Miscellaneous_Mathematical_Symbols_A', displayName: 'Miscellaneous Mathematical Symbols A', start: 0x27C0, end: 0x27EF },
  { name: 'Supplemental_Arrows_A', displayName: 'Supplemental Arrows A', start: 0x27F0, end: 0x27FF },
  { name: 'Braille_Patterns', displayName: 'Braille Patterns', start: 0x2800, end: 0x28FF },
  { name: 'Supplemental_Arrows_B', displayName: 'Supplemental Arrows B', start: 0x2900, end: 0x297F },
  { name: 'Miscellaneous_Mathematical_Symbols_B', displayName: 'Miscellaneous Mathematical Symbols B', start: 0x2980, end: 0x29FF },
  { name: 'Supplemental_Mathematical_Operators', displayName: 'Supplemental Mathematical Operators', start: 0x2A00, end: 0x2AFF },
  { name: 'Miscellaneous_Symbols_And_Arrows', displayName: 'Miscellaneous Symbols And Arrows', start: 0x2B00, end: 0x2BFF },
  { name: 'Glagolitic', displayName: 'Glagolitic', start: 0x2C00, end: 0x2C5F },
  { name: 'Latin_Extended_C', displayName: 'Latin Extended C', start: 0x2C60, end: 0x2C7F },
  { name: 'Coptic', displayName: 'Coptic', start: 0x2C80, end: 0x2CFF },
  { name: 'Georgian_Supplement', displayName: 'Georgian Supplement', start: 0x2D00, end: 0x2D2F },
  { name: 'Tifinagh', displayName: 'Tifinagh', start: 0x2D30, end: 0x2D7F },
  { name: 'Ethiopic_Extended', displayName: 'Ethiopic Extended', start: 0x2D80, end: 0x2DDF },
  { name: 'Cyrillic_Extended_A', displayName: 'Cyrillic Extended A', start: 0x2DE0, end: 0x2DFF },
  { name: 'Supplemental_Punctuation', displayName: 'Supplemental Punctuation', start: 0x2E00, end: 0x2E7F },
  { name: 'CJK_Radicals_Supplement', displayName: 'CJK Radicals Supplement', start: 0x2E80, end: 0x2EFF },
  { name: 'Kangxi_Radicals', displayName: 'Kangxi Radicals', start: 0x2F00, end: 0x2FDF },
  { name: 'Ideographic_Description_Characters', displayName: 'Ideographic Description Characters', start: 0x2FF0, end: 0x2FFF },
  { name: 'CJK_Symbols_And_Punctuation', displayName: 'CJK Symbols And Punctuation', start: 0x3000, end: 0x303F },
  { name: 'Hiragana', displayName: 'Hiragana', start: 0x3040, end: 0x309F },
  { name: 'Katakana', displayName: 'Katakana', start: 0x30A0, end: 0x30FF },
  { name: 'Bopomofo', displayName: 'Bopomofo', start: 0x3100, end: 0x312F },
  { name: 'Hangul_Compatibility_Jamo', displayName: 'Hangul Compatibility Jamo', start: 0x3130, end: 0x318F },
  { name: 'Kanbun', displayName: 'Kanbun', start: 0x3190, end: 0x319F },
  { name: 'Bopomofo_Extended', displayName: 'Bopomofo Extended', start: 0x31A0, end: 0x31BF },
  { name: 'CJK_Strokes', displayName: 'CJK Strokes', start: 0x31C0, end: 0x31EF },
  { name: 'Katakana_Phonetic_Extensions', displayName: 'Katakana Phonetic Extensions', start: 0x31F0, end: 0x31FF },
  { name: 'Enclosed_CJK_Letters_And_Months', displayName: 'Enclosed CJK Letters And Months', start: 0x3200, end: 0x32FF },
  { name: 'CJK_Compatibility', displayName: 'CJK Compatibility', start: 0x3300, end: 0x33FF },
  { name: 'CJK_Unified_Ideographs_Extension_A', displayName: 'CJK Unified Ideographs Extension A', start: 0x3400, end: 0x4DBF },
  { name: 'Yijing_Hexagram_Symbols', displayName: 'Yijing Hexagram Symbols', start: 0x4DC0, end: 0x4DFF },
  { name: 'CJK_Unified_Ideographs', displayName: 'CJK Unified Ideographs', start: 0x4E00, end: 0x9FFF },
  { name: 'Yi_Syllables', displayName: 'Yi Syllables', start: 0xA000, end: 0xA48F },
  { name: 'Yi_Radicals', displayName: 'Yi Radicals', start: 0xA490, end: 0xA4CF },
  { name: 'Lisu', displayName: 'Lisu', start: 0xA4D0, end: 0xA4FF },
  { name: 'Vai', displayName: 'Vai', start: 0xA500, end: 0xA63F },
  { name: 'Cyrillic_Extended_B', displayName: 'Cyrillic Extended B', start: 0xA640, end: 0xA69F },
  { name: 'Bamum', displayName: 'Bamum', start: 0xA6A0, end: 0xA6FF },
  { name: 'Modifier_Tone_Letters', displayName: 'Modifier Tone Letters', start: 0xA700, end: 0xA71F },
  { name: 'Latin_Extended_D', displayName: 'Latin Extended D', start: 0xA720, end: 0xA7FF },
  { name: 'Syloti_Nagri', displayName: 'Syloti Nagri', start: 0xA800, end: 0xA82F },
  { name: 'Common_Indic_Number_Forms', displayName: 'Common Indic Number Forms', start: 0xA830, end: 0xA83F },
  { name: 'Phags_Pa', displayName: 'Phags Pa', start: 0xA840, end: 0xA87F },
  { name: 'Saurashtra', displayName: 'Saurashtra', start: 0xA880, end: 0xA8DF },
  { name: 'Devanagari_Extended', displayName: 'Devanagari Extended', start: 0xA8E0, end: 0xA8FF },
  { name: 'Kayah_Li', displayName: 'Kayah Li', start: 0xA900, end: 0xA92F },
  { name: 'Rejang', displayName: 'Rejang', start: 0xA930, end: 0xA95F },
  { name: 'Hangul_Jamo_Extended_A', displayName: 'Hangul Jamo Extended A', start: 0xA960, end: 0xA97F },
  { name: 'Javanese', displayName: 'Javanese', start: 0xA980, end: 0xA9DF },
  { name: 'Myanmar_Extended_B', displayName: 'Myanmar Extended B', start: 0xA9E0, end: 0xA9FF },
  { name: 'Cham', displayName: 'Cham', start: 0xAA00, end: 0xAA5F },
  { name: 'Myanmar_Extended_A', displayName: 'Myanmar Extended A', start: 0xAA60, end: 0xAA7F },
  { name: 'Tai_Viet', displayName: 'Tai Viet', start: 0xAA80, end: 0xAADF },
  { name: 'Meetei_Mayek_Extensions', displayName: 'Meetei Mayek Extensions', start: 0xAAE0, end: 0xAAFF },
  { name: 'Ethiopic_Extended_A', displayName: 'Ethiopic Extended A', start: 0xAB00, end: 0xAB2F },
  { name: 'Latin_Extended_E', displayName: 'Latin Extended E', start: 0xAB30, end: 0xAB6F },
  { name: 'Cherokee_Supplement', displayName: 'Cherokee Supplement', start: 0xAB70, end: 0xABBF },
  { name: 'Meetei_Mayek', displayName: 'Meetei Mayek', start: 0xABC0, end: 0xABFF },
  { name: 'Hangul_Syllables', displayName: 'Hangul Syllables', start: 0xAC00, end: 0xD7AF },
  { name: 'Hangul_Jamo_Extended_B', displayName: 'Hangul Jamo Extended B', start: 0xD7B0, end: 0xD7FF },
  { name: 'High_Surrogates', displayName: 'High Surrogates', start: 0xD800, end: 0xDB7F },
  { name: 'High_Private_Use_Surrogates', displayName: 'High Private Use Surrogates', start: 0xDB80, end: 0xDBFF },
  { name: 'Low_Surrogates', displayName: 'Low Surrogates', start: 0xDC00, end: 0xDFFF },
  { name: 'Private_Use_Area', displayName: 'Private Use Area', start: 0xE000, end: 0xF8FF },
  { name: 'CJK_Compatibility_Ideographs', displayName: 'CJK Compatibility Ideographs', start: 0xF900, end: 0xFAFF },
  { name: 'Alphabetic_Presentation_Forms', displayName: 'Alphabetic Presentation Forms', start: 0xFB00, end: 0xFB4F },
  { name: 'Arabic_Presentation_Forms_A', displayName: 'Arabic Presentation Forms A', start: 0xFB50, end: 0xFDFF },
  { name: 'Variation_Selectors', displayName: 'Variation Selectors', start: 0xFE00, end: 0xFE0F },
  { name: 'Vertical_Forms', displayName: 'Vertical Forms', start: 0xFE10, end: 0xFE1F },
  { name: 'Combining_Half_Marks', displayName: 'Combining Half Marks', start: 0xFE20, end: 0xFE2F },
  { name: 'CJK_Compatibility_Forms', displayName: 'CJK Compatibility Forms', start: 0xFE30, end: 0xFE4F },
  { name: 'Small_Form_Variants', displayName: 'Small Form Variants', start: 0xFE50, end: 0xFE6F },
  { name: 'Arabic_Presentation_Forms_B', displayName: 'Arabic Presentation Forms B', start: 0xFE70, end: 0xFEFF },
  { name: 'Halfwidth_And_Fullwidth_Forms', displayName: 'Halfwidth And Fullwidth Forms', start: 0xFF00, end: 0xFFEF },
  { name: 'Specials', displayName: 'Specials', start: 0xFFF0, end: 0xFFFF },
  { name: 'Linear_B_Syllabary', displayName: 'Linear B Syllabary', start: 0x10000, end: 0x1007F },
  { name: 'Linear_B_Ideograms', displayName: 'Linear B Ideograms', start: 0x10080, end: 0x100FF },
  { name: 'Aegean_Numbers', displayName: 'Aegean Numbers', start: 0x10100, end: 0x1013F },
  { name: 'Ancient_Greek_Numbers', displayName: 'Ancient Greek Numbers', start: 0x10140, end: 0x1018F },
  { name: 'Ancient_Symbols', displayName: 'Ancient Symbols', start: 0x10190, end: 0x101CF },
  { name: 'Phaistos_Disc', displayName: 'Phaistos Disc', start: 0x101D0, end: 0x101FF },
  { name: 'Lycian', displayName: 'Lycian', start: 0x10280, end: 0x1029F },
  { name: 'Carian', displayName: 'Carian', start: 0x102A0, end: 0x102DF },
  { name: 'Coptic_Epact_Numbers', displayName: 'Coptic Epact Numbers', start: 0x102E0, end: 0x102FF },
  { name: 'Old_Italic', displayName: 'Old Italic', start: 0x10300, end: 0x1032F },
  { name: 'Gothic', displayName: 'Gothic', start: 0x10330, end: 0x1034F },
  { name: 'Old_Permic', displayName: 'Old Permic', start: 0x10350, end: 0x1037F },
  { name: 'Ugaritic', displayName: 'Ugaritic', start: 0x10380, end: 0x1039F },
  { name: 'Old_Persian', displayName: 'Old Persian', start: 0x103A0, end: 0x103DF },
  { name: 'Deseret', displayName: 'Deseret', start: 0x10400, end: 0x1044F },
  { name: 'Shavian', displayName: 'Shavian', start: 0x10450, end: 0x1047F },
  { name: 'Osmanya', displayName: 'Osmanya', start: 0x10480, end: 0x104AF },
  { name: 'Osage', displayName: 'Osage', start: 0x104B0, end: 0x104FF },
  { name: 'Elbasan', displayName: 'Elbasan', start: 0x10500, end: 0x1052F },
  { name: 'Caucasian_Albanian', displayName: 'Caucasian Albanian', start: 0x10530, end: 0x1056F },
  { name: 'Vithkuqi', displayName: 'Vithkuqi', start: 0x10570, end: 0x105BF },
  { name: 'Todhri', displayName: 'Todhri', start: 0x105C0, end: 0x105FF },
  { name: 'Linear_A', displayName: 'Linear A', start: 0x10600, end: 0x1077F },
  { name: 'Latin_Extended_F', displayName: 'Latin Extended F', start: 0x10780, end: 0x107BF },
  { name: 'Cypriot_Syllabary', displayName: 'Cypriot Syllabary', start: 0x10800, end: 0x1083F },
  { name: 'Imperial_Aramaic', displayName: 'Imperial Aramaic', start: 0x10840, end: 0x1085F },
  { name: 'Palmyrene', displayName: 'Palmyrene', start: 0x10860, end: 0x1087F },
  { name: 'Nabataean', displayName: 'Nabataean', start: 0x10880, end: 0x108AF },
  { name: 'Hatran', displayName: 'Hatran', start: 0x108E0, end: 0x108FF },
  { name: 'Phoenician', displayName: 'Phoenician', start: 0x10900, end: 0x1091F },
  { name: 'Lydian', displayName: 'Lydian', start: 0x10920, end: 0x1093F },
  { name: 'Meroitic_Hieroglyphs', displayName: 'Meroitic Hieroglyphs', start: 0x10980, end: 0x1099F },
  { name: 'Meroitic_Cursive', displayName: 'Meroitic Cursive', start: 0x109A0, end: 0x109FF },
  { name: 'Kharoshthi', displayName: 'Kharoshthi', start: 0x10A00, end: 0x10A5F },
  { name: 'Old_South_Arabian', displayName: 'Old South Arabian', start: 0x10A60, end: 0x10A7F },
  { name: 'Old_North_Arabian', displayName: 'Old North Arabian', start: 0x10A80, end: 0x10A9F },
  { name: 'Manichaean', displayName: 'Manichaean', start: 0x10AC0, end: 0x10AFF },
  { name: 'Avestan', displayName: 'Avestan', start: 0x10B00, end: 0x10B3F },
  { name: 'Inscriptional_Parthian', displayName: 'Inscriptional Parthian', start: 0x10B40, end: 0x10B5F },
  { name: 'Inscriptional_Pahlavi', displayName: 'Inscriptional Pahlavi', start: 0x10B60, end: 0x10B7F },
  { name: 'Psalter_Pahlavi', displayName: 'Psalter Pahlavi', start: 0x10B80, end: 0x10BAF },
  { name: 'Old_Turkic', displayName: 'Old Turkic', start: 0x10C00, end: 0x10C4F },
  { name: 'Old_Hungarian', displayName: 'Old Hungarian', start: 0x10C80, end: 0x10CFF },
  { name: 'Hanifi_Rohingya', displayName: 'Hanifi Rohingya', start: 0x10D00, end: 0x10D3F },
  { name: 'Garay', displayName: 'Garay', start: 0x10D40, end: 0x10D8F },
  { name: 'Rumi_Numeral_Symbols', displayName: 'Rumi Numeral Symbols', start: 0x10E60, end: 0x10E7F },
  { name: 'Yezidi', displayName: 'Yezidi', start: 0x10E80, end: 0x10EBF },
  { name: 'Arabic_Extended_C', displayName: 'Arabic Extended C', start: 0x10EC0, end: 0x10EFF },
  { name: 'Old_Sogdian', displayName: 'Old Sogdian', start: 0x10F00, end: 0x10F2F },
  { name: 'Sogdian', displayName: 'Sogdian', start: 0x10F30, end: 0x10F6F },
  { name: 'Old_Uyghur', displayName: 'Old Uyghur', start: 0x10F70, end: 0x10FAF },
  { name: 'Chorasmian', displayName: 'Chorasmian', start: 0x10FB0, end: 0x10FDF },
  { name: 'Elymaic', displayName: 'Elymaic', start: 0x10FE0, end: 0x10FFF },
  { name: 'Brahmi', displayName: 'Brahmi', start: 0x11000, end: 0x1107F },
  { name: 'Kaithi', displayName: 'Kaithi', start: 0x11080, end: 0x110CF },
  { name: 'Sora_Sompeng', displayName: 'Sora Sompeng', start: 0x110D0, end: 0x110FF },
  { name: 'Chakma', displayName: 'Chakma', start: 0x11100, end: 0x1114F },
  { name: 'Mahajani', displayName: 'Mahajani', start: 0x11150, end: 0x1117F },
  { name: 'Sharada', displayName: 'Sharada', start: 0x11180, end: 0x111DF },
  { name: 'Sinhala_Archaic_Numbers', displayName: 'Sinhala Archaic Numbers', start: 0x111E0, end: 0x111FF },
  { name: 'Khojki', displayName: 'Khojki', start: 0x11200, end: 0x1124F },
  { name: 'Multani', displayName: 'Multani', start: 0x11280, end: 0x112AF },
  { name: 'Khudawadi', displayName: 'Khudawadi', start: 0x112B0, end: 0x112FF },
  { name: 'Grantha', displayName: 'Grantha', start: 0x11300, end: 0x1137F },
  { name: 'Tulu_Tigalari', displayName: 'Tulu Tigalari', start: 0x11380, end: 0x113FF },
  { name: 'Newa', displayName: 'Newa', start: 0x11400, end: 0x1147F },
  { name: 'Tirhuta', displayName: 'Tirhuta', start: 0x11480, end: 0x114DF },
  { name: 'Siddham', displayName: 'Siddham', start: 0x11580, end: 0x115FF },
  { name: 'Modi', displayName: 'Modi', start: 0x11600, end: 0x1165F },
  { name: 'Mongolian_Supplement', displayName: 'Mongolian Supplement', start: 0x11660, end: 0x1167F },
  { name: 'Takri', displayName: 'Takri', start: 0x11680, end: 0x116CF },
  { name: 'Myanmar_Extended_C', displayName: 'Myanmar Extended C', start: 0x116D0, end: 0x116FF },
  { name: 'Ahom', displayName: 'Ahom', start: 0x11700, end: 0x1174F },
  { name: 'Dogra', displayName: 'Dogra', start: 0x11800, end: 0x1184F },
  { name: 'Warang_Citi', displayName: 'Warang Citi', start: 0x118A0, end: 0x118FF },
  { name: 'Dives_Akuru', displayName: 'Dives Akuru', start: 0x11900, end: 0x1195F },
  { name: 'Nandinagari', displayName: 'Nandinagari', start: 0x119A0, end: 0x119FF },
  { name: 'Zanabazar_Square', displayName: 'Zanabazar Square', start: 0x11A00, end: 0x11A4F },
  { name: 'Soyombo', displayName: 'Soyombo', start: 0x11A50, end: 0x11AAF },
  { name: 'Unified_Canadian_Aboriginal_Syllabics_Extended_A', displayName: 'Unified Canadian Aboriginal Syllabics Extended A', start: 0x11AB0, end: 0x11ABF },
  { name: 'Pau_Cin_Hau', displayName: 'Pau Cin Hau', start: 0x11AC0, end: 0x11AFF },
  { name: 'Devanagari_Extended_A', displayName: 'Devanagari Extended A', start: 0x11B00, end: 0x11B5F },
  { name: 'Sunuwar', displayName: 'Sunuwar', start: 0x11BC0, end: 0x11BFF },
  { name: 'Bhaiksuki', displayName: 'Bhaiksuki', start: 0x11C00, end: 0x11C6F },
  { name: 'Marchen', displayName: 'Marchen', start: 0x11C70, end: 0x11CBF },
  { name: 'Masaram_Gondi', displayName: 'Masaram Gondi', start: 0x11D00, end: 0x11D5F },
  { name: 'Gunjala_Gondi', displayName: 'Gunjala Gondi', start: 0x11D60, end: 0x11DAF },
  { name: 'Makasar', displayName: 'Makasar', start: 0x11EE0, end: 0x11EFF },
  { name: 'Kawi', displayName: 'Kawi', start: 0x11F00, end: 0x11F5F },
  { name: 'Lisu_Supplement', displayName: 'Lisu Supplement', start: 0x11FB0, end: 0x11FBF },
  { name: 'Tamil_Supplement', displayName: 'Tamil Supplement', start: 0x11FC0, end: 0x11FFF },
  { name: 'Cuneiform', displayName: 'Cuneiform', start: 0x12000, end: 0x123FF },
  { name: 'Cuneiform_Numbers_And_Punctuation', displayName: 'Cuneiform Numbers And Punctuation', start: 0x12400, end: 0x1247F },
  { name: 'Early_Dynastic_Cuneiform', displayName: 'Early Dynastic Cuneiform', start: 0x12480, end: 0x1254F },
  { name: 'Cypro_Minoan', displayName: 'Cypro Minoan', start: 0x12F90, end: 0x12FFF },
  { name: 'Egyptian_Hieroglyphs', displayName: 'Egyptian Hieroglyphs', start: 0x13000, end: 0x1342F },
  { name: 'Egyptian_Hieroglyph_Format_Controls', displayName: 'Egyptian Hieroglyph Format Controls', start: 0x13430, end: 0x1345F },
  { name: 'Egyptian_Hieroglyphs_Extended_A', displayName: 'Egyptian Hieroglyphs Extended A', start: 0x13460, end: 0x143FF },
  { name: 'Anatolian_Hieroglyphs', displayName: 'Anatolian Hieroglyphs', start: 0x14400, end: 0x1467F },
  { name: 'Gurung_Khema', displayName: 'Gurung Khema', start: 0x16100, end: 0x1613F },
  { name: 'Bamum_Supplement', displayName: 'Bamum Supplement', start: 0x16800, end: 0x16A3F },
  { name: 'Mro', displayName: 'Mro', start: 0x16A40, end: 0x16A6F },
  { name: 'Tangsa', displayName: 'Tangsa', start: 0x16A70, end: 0x16ACF },
  { name: 'Bassa_Vah', displayName: 'Bassa Vah', start: 0x16AD0, end: 0x16AFF },
  { name: 'Pahawh_Hmong', displayName: 'Pahawh Hmong', start: 0x16B00, end: 0x16B8F },
  { name: 'Kirat_Rai', displayName: 'Kirat Rai', start: 0x16D40, end: 0x16D7F },
  { name: 'Medefaidrin', displayName: 'Medefaidrin', start: 0x16E40, end: 0x16E9F },
  { name: 'Miao', displayName: 'Miao', start: 0x16F00, end: 0x16F9F },
  { name: 'Ideographic_Symbols_And_Punctuation', displayName: 'Ideographic Symbols And Punctuation', start: 0x16FE0, end: 0x16FFF },
  { name: 'Tangut', displayName: 'Tangut', start: 0x17000, end: 0x187FF },
  { name: 'Tangut_Components', displayName: 'Tangut Components', start: 0x18800, end: 0x18AFF },
  { name: 'Khitan_Small_Script', displayName: 'Khitan Small Script', start: 0x18B00, end: 0x18CFF },
  { name: 'Tangut_Supplement', displayName: 'Tangut Supplement', start: 0x18D00, end: 0x18D7F },
  { name: 'Kana_Extended_B', displayName: 'Kana Extended B', start: 0x1AFF0, end: 0x1AFFF },
  { name: 'Kana_Supplement', displayName: 'Kana Supplement', start: 0x1B000, end: 0x1B0FF },
  { name: 'Kana_Extended_A', displayName: 'Kana Extended A', start: 0x1B100, end: 0x1B12F },
  { name: 'Small_Kana_Extension', displayName: 'Small Kana Extension', start: 0x1B130, end: 0x1B16F },
  { name: 'Nushu', displayName: 'Nushu', start: 0x1B170, end: 0x1B2FF },
  { name: 'Duployan', displayName: 'Duployan', start: 0x1BC00, end: 0x1BC9F },
  { name: 'Shorthand_Format_Controls', displayName: 'Shorthand Format Controls', start: 0x1BCA0, end: 0x1BCAF },
  { name: 'Symbols_For_Legacy_Computing_Supplement', displayName: 'Symbols For Legacy Computing Supplement', start: 0x1CC00, end: 0x1CEBF },
  { name: 'Znamenny_Musical_Notation', displayName: 'Znamenny Musical Notation', start: 0x1CF00, end: 0x1CFCF },
  { name: 'Byzantine_Musical_Symbols', displayName: 'Byzantine Musical Symbols', start: 0x1D000, end: 0x1D0FF },
  { name: 'Musical_Symbols', displayName: 'Musical Symbols', start: 0x1D100, end: 0x1D1FF },
  { name: 'Ancient_Greek_Musical_Notation', displayName: 'Ancient Greek Musical Notation', start: 0x1D200, end: 0x1D24F },
  { name: 'Kaktovik_Numerals', displayName: 'Kaktovik Numerals', start: 0x1D2C0, end: 0x1D2DF },
  { name: 'Mayan_Numerals', displayName: 'Mayan Numerals', start: 0x1D2E0, end: 0x1D2FF },
  { name: 'Tai_Xuan_Jing_Symbols', displayName: 'Tai Xuan Jing Symbols', start: 0x1D300, end: 0x1D35F },
  { name: 'Counting_Rod_Numerals', displayName: 'Counting Rod Numerals', start: 0x1D360, end: 0x1D37F },
  { name: 'Mathematical_Alphanumeric_Symbols', displayName: 'Mathematical Alphanumeric Symbols', start: 0x1D400, end: 0x1D7FF },
  { name: 'Sutton_SignWriting', displayName: 'Sutton SignWriting', start: 0x1D800, end: 0x1DAAF },
  { name: 'Latin_Extended_G', displayName: 'Latin Extended G', start: 0x1DF00, end: 0x1DFFF },
  { name: 'Glagolitic_Supplement', displayName: 'Glagolitic Supplement', start: 0x1E000, end: 0x1E02F },
  { name: 'Cyrillic_Extended_D', displayName: 'Cyrillic Extended D', start: 0x1E030, end: 0x1E08F },
  { name: 'Nyiakeng_Puachue_Hmong', displayName: 'Nyiakeng Puachue Hmong', start: 0x1E100, end: 0x1E14F },
  { name: 'Toto', displayName: 'Toto', start: 0x1E290, end: 0x1E2BF },
  { name: 'Wancho', displayName: 'Wancho', start: 0x1E2C0, end: 0x1E2FF },
  { name: 'Nag_Mundari', displayName: 'Nag Mundari', start: 0x1E4D0, end: 0x1E4FF },
  { name: 'Ol_Onal', displayName: 'Ol Onal', start: 0x1E5D0, end: 0x1E5FF },
  { name: 'Ethiopic_Extended_B', displayName: 'Ethiopic Extended B', start: 0x1E7E0, end: 0x1E7FF },
  { name: 'Mende_Kikakui', displayName: 'Mende Kikakui', start: 0x1E800, end: 0x1E8DF },
  { name: 'Adlam', displayName: 'Adlam', start: 0x1E900, end: 0x1E95F },
  { name: 'Indic_Siyaq_Numbers', displayName: 'Indic Siyaq Numbers', start: 0x1EC70, end: 0x1ECBF },
  { name: 'Ottoman_Siyaq_Numbers', displayName: 'Ottoman Siyaq Numbers', start: 0x1ED00, end: 0x1ED4F },
  { name: 'Arabic_Mathematical_Alphabetic_Symbols', displayName: 'Arabic Mathematical Alphabetic Symbols', start: 0x1EE00, end: 0x1EEFF },
  { name: 'Mahjong_Tiles', displayName: 'Mahjong Tiles', start: 0x1F000, end: 0x1F02F },
  { name: 'Domino_Tiles', displayName: 'Domino Tiles', start: 0x1F030, end: 0x1F09F },
  { name: 'Playing_Cards', displayName: 'Playing Cards', start: 0x1F0A0, end: 0x1F0FF },
  { name: 'Enclosed_Alphanumeric_Supplement', displayName: 'Enclosed Alphanumeric Supplement', start: 0x1F100, end: 0x1F1FF },
  { name: 'Enclosed_Ideographic_Supplement', displayName: 'Enclosed Ideographic Supplement', start: 0x1F200, end: 0x1F2FF },
  { name: 'Miscellaneous_Symbols_And_Pictographs', displayName: 'Miscellaneous Symbols And Pictographs', start: 0x1F300, end: 0x1F5FF },
  { name: 'Emoticons', displayName: 'Emoticons', start: 0x1F600, end: 0x1F64F },
  { name: 'Ornamental_Dingbats', displayName: 'Ornamental Dingbats', start: 0x1F650, end: 0x1F67F },
  { name: 'Transport_And_Map_Symbols', displayName: 'Transport And Map Symbols', start: 0x1F680, end: 0x1F6FF },
  { name: 'Alchemical_Symbols', displayName: 'Alchemical Symbols', start: 0x1F700, end: 0x1F77F },
  { name: 'Geometric_Shapes_Extended', displayName: 'Geometric Shapes Extended', start: 0x1F780, end: 0x1F7FF },
  { name: 'Supplemental_Arrows_C', displayName: 'Supplemental Arrows C', start: 0x1F800, end: 0x1F8FF },
  { name: 'Supplemental_Symbols_And_Pictographs', displayName: 'Supplemental Symbols And Pictographs', start: 0x1F900, end: 0x1F9FF },
  { name: 'Chess_Symbols', displayName: 'Chess Symbols', start: 0x1FA00, end: 0x1FA6F },
  { name: 'Symbols_And_Pictographs_Extended_A', displayName: 'Symbols And Pictographs Extended A', start: 0x1FA70, end: 0x1FAFF },
  { name: 'Symbols_For_Legacy_Computing', displayName: 'Symbols For Legacy Computing', start: 0x1FB00, end: 0x1FBFF },
  { name: 'CJK_Unified_Ideographs_Extension_B', displayName: 'CJK Unified Ideographs Extension B', start: 0x20000, end: 0x2A6DF },
  { name: 'CJK_Unified_Ideographs_Extension_C', displayName: 'CJK Unified Ideographs Extension C', start: 0x2A700, end: 0x2B73F },
  { name: 'CJK_Unified_Ideographs_Extension_D', displayName: 'CJK Unified Ideographs Extension D', start: 0x2B740, end: 0x2B81F },
  { name: 'CJK_Unified_Ideographs_Extension_E', displayName: 'CJK Unified Ideographs Extension E', start: 0x2B820, end: 0x2CEAF },
  { name: 'CJK_Unified_Ideographs_Extension_F', displayName: 'CJK Unified Ideographs Extension F', start: 0x2CEB0, end: 0x2EBEF },
  { name: 'CJK_Unified_Ideographs_Extension_I', displayName: 'CJK Unified Ideographs Extension I', start: 0x2EBF0, end: 0x2EE5F },
  { name: 'CJK_Compatibility_Ideographs_Supplement', displayName: 'CJK Compatibility Ideographs Supplement', start: 0x2F800, end: 0x2FA1F },
  { name: 'CJK_Unified_Ideographs_Extension_G', displayName: 'CJK Unified Ideographs Extension G', start: 0x30000, end: 0x3134F },
  { name: 'CJK_Unified_Ideographs_Extension_H', displayName: 'CJK Unified Ideographs Extension H', start: 0x31350, end: 0x323AF },
  { name: 'Tags', displayName: 'Tags', start: 0xE0000, end: 0xE007F },
  { name: 'Variation_Selectors_Supplement', displayName: 'Variation Selectors Supplement', start: 0xE0100, end: 0xE01EF },
  { name: 'Supplementary_Private_Use_Area_A', displayName: 'Supplementary Private Use Area A', start: 0xF0000, end: 0xFFFFF },
  { name: 'Supplementary_Private_Use_Area_B', displayName: 'Supplementary Private Use Area B', start: 0x100000, end: 0x10FFFF },
]

export function getBlockSize(block: UnicodeBlock): number {
  return block.end - block.start + 1
}

// Get 4 representative characters from a block (quartile first chars)
export function getQuartileChars(block: UnicodeBlock): number[] {
  const size = getBlockSize(block)
  const quartileSize = Math.floor(size / 4)

  return [
    block.start, // Q1
    block.start + quartileSize, // Q2
    block.start + quartileSize * 2, // Q3
    block.start + quartileSize * 3, // Q4
  ]
}

// Filter blocks by BMP only (U+0000 to U+FFFF)
export const BMP_BLOCKS = UNICODE_BLOCKS.filter((b) => b.start <= 0xFFFF)

// Get block by codepoint
export function getBlockByCodepoint(codepoint: number): UnicodeBlock | undefined {
  return UNICODE_BLOCKS.find((b) => codepoint >= b.start && codepoint <= b.end)
}
